Question and answers models added.
MrAlejandro/qna pull request #1
Opened 2019-04-11 18:41 UTC by MrAlejandro

2019-04-12 08:26 UTC, vkurennov requested changes

2019-04-12 08:26 UTC, vkurennov commented on app/models/question.rb
> +  has_many :answers
тут нужна опция, при которой удаление вопроса также удалит и связанные ответы. и не забудь протестировать эту опцию, shoulda-mathchers это умеет

2019-04-12 16:46 UTC, MrAlejandro commented on app/models/question.rb
> +  has_many :answers
done

2019-04-13 10:02 UTC, vkurennov approved these changes

2019-04-13 18:19 UTC, merged