Create question user story implemented
MrAlejandro/qna pull request #3
Opened 2019-04-15 18:29 UTC by MrAlejandro

2019-04-17 07:28 UTC, vkurennov requested changes

2019-04-17 07:28 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    current_user.save
очень не логично сохранять юзера, ведь а) сам юзер не менялся, б) почему вдруг AnswersController сохраняет юзера, а не ответ? Работай с нужным объектом, тогда все будет логично

2019-04-17 07:28 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to @question, notice: @answer.errors.full_messages.join(', ')
плохое решение, несмотря на то, что ошибки ты передаешь. дело в том, что при редиректе все, что ввел пользователь исчезнет и ему надо будет весь ответ заново набирать. представь себя в такой ситуации, чтобы ты сказал о разработчике сайта?
Поэтому здесь нужен рендер страницы, где была форма (questions/show) и ошибки валидации тогда нужно в виде отображать через стандартный паршл ошибок.

2019-04-17 07:28 UTC, vkurennov commented on app/controllers/questions_controller.rb
>      if @question.save
здесь же ты вопрос сохраняешь, а не юзера, почему не сделать также в контроллере ответов?

2019-04-17 07:28 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if question.author?(current_user)
1. Вот смотри, у тебя метод `author?` дублируется и вопроса и у  ответа. А если его перенести в модель User (ведь "спрашивать" у юзера, является ли он автором того или иного объекта гораздо логичнее), то метод будет в одном месте и работать с любыми объектами.
2. Определись, ты используешь методы-хелепры во всех контроллерах (как question здесь) или инстанс-переменные (как в контроллере ответов) и выбери один способ и используй его везде.

2019-04-17 07:28 UTC, vkurennov commented on app/helpers/answers_helper.rb
> +  def answer
этого не стоили выносить в хелпер, т.к. будет запутывать, особенно, если появится аналогичный метод в контроллере

2019-04-17 07:28 UTC, vkurennov commented on app/models/answer.rb
> +    user && author.id == user.id
здесь у тебя верная идея сравнивать по id, но реализация не верная. по id сравнивают, чтобы не загружать ассоциацию из базы (т.е. не делать к ней лишний запрос), поэтому надо сравнивать не `author.id` (т.е. загрузит ассоциацию в память и у нее взять id),  а по полю `author_id`, где уже содержится нужное значение и оно уже загружено в память у данного объекта.

2019-04-17 07:28 UTC, vkurennov commented on app/models/question.rb
> +  def author?(user)
а вот и дублирование, о ктором я говорил. Тебя не смутило, что ты написал 2 одинаковых метода в разных классах? а должно было, т.к. это верный признак того, что ты что-то делаешь не так.
Кстати, а где тесты модели на эти методы? Любой код, который ты пишешь в каком-либо классе (не важно, контроллер или модель) нужно покрывать тестами.

2019-04-17 07:28 UTC, vkurennov commented on app/views/layouts/application.html.erb
>    </head>
лейаут тоже надо на slim перевести

2019-04-17 07:28 UTC, vkurennov commented on app/views/questions/new.html.slim
> += form_with model: question do |f|
добавь здесь `local: true`, иначе форма может некорректно работать (подробнее об этом в след. уроке)

2019-04-17 07:28 UTC, vkurennov commented on app/views/questions/show.html.slim
> += @answers.each do |answer|
здесь не долждно быть `=`, а должно быть `-`, т.к. тебе не нужно выводить результат метода each (он возвращает всю коллекцию), посмотри на странице в браузере как это выглядит

2019-04-17 07:28 UTC, vkurennov commented on app/views/questions/show.html.slim
> += form_with model: [question, answer], local: true do |f|
тут у тебя стоит answer, который возвращает Answer.new, а значит, данные, которые ввел пользователь сотрутся, даже если в контроллере ты сделаешь ренедр вместо редиректа. Тут нужно использовать переменную, которая устанавливается в контроллере

2019-04-17 07:28 UTC, vkurennov commented on db/migrate/20190416180144_add_author_id_to_question.rb
> +    add_column :questions, :author_id, :integer
так добавлять внешние ключи неэффективно. нужно еще на них вешать индекс и опцию foreign_key, но add_colum не поддерживает эти опции. Поэтому для добавления полей ассоциаций используй метод add_belongs_to/add_reference (это элиасы), они сразу добавят индекс и  у них можно указать опцию `foreign_key: true`, чтобы включить контроль целостности на уровне БД

2019-04-17 07:28 UTC, vkurennov commented on db/migrate/20190416191423_add_author_id_to_answers.rb
> +    add_column :answers, :author_id, :integer
тут тоже надо использовать другой метод

2019-04-17 07:28 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
тут нужно протестировать связь с залогиненным юзером

2019-04-17 07:28 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      question.answers = [answer]
что за странный способ устанавливать ассоциацию "с другой стороны"? ты можешь использовать ассоциации answer. Это во-первых, а во-вторых, если нужно создать связанные объекты, ты можешь делать это сразу в фабриках (только сначала надо вопрос создать, а потом ответ):

```
let(:question) { create(:question) }
let(:answer) { create(:answer, question: question) }
```

2019-04-17 07:28 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: answer.id } }.to change(question.answers, :count).by(-1)
здесь в change должен быть просто Answer, т.к. для удаления не важны ассоциации

2019-04-17 07:28 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    it 'User that does not own the answer cannot delete it' do
а какой рендер/редирект, если это не автор? Лучше всего сделать 2 контекста: для автора и для не автора, тогда тесты будут логично сгруппированы

2019-04-17 07:28 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
тут нужно протестировать связь с залогиненным юзером

2019-04-17 07:28 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      describe 'by owner of the question' do
лучше использовать context, а не describe

2019-04-17 07:28 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      describe 'by other user' do
какой рендер/редирект в этом случае?

2019-04-17 07:28 UTC, vkurennov commented on spec/factories/answers.rb
> +    question { create(:question) }
если ассоциация по имени совпадает с именем фабрики, то можно писать сокращенно, просто `question`

2019-04-17 07:28 UTC, vkurennov commented on spec/factories/answers.rb
> +    author { create(:user) }
почитай, [как задаются ассоциации в фабриках](https://www.rubydoc.info/gems/factory_bot/file/GETTING_STARTED.md#Associations)

2019-04-17 07:28 UTC, vkurennov commented on spec/features/answers/destroy_spec.rb
> +  scenario 'User can delete answer that belongs to him' do
если еще как минимум 2 сценария: для не-автора и для незалогиненного юзера

2019-04-17 07:28 UTC, vkurennov commented on spec/features/answers/destroy_spec.rb
> +    expect(page).to have_content 'Answer has been deleted.'
этого не достаточно, надо проверить, что до удаления текст вопроса есть на странице, а после, что его нет

2019-04-17 07:28 UTC, vkurennov commented on spec/features/question/destroy_spec.rb
> +feature 'User can delete question', %q{
см. замечания к аналогичной фиче для ответов

2019-04-17 07:28 UTC, vkurennov commented on spec/features/question/index_spec.rb
> +    questions.each do |question|
тест верный, но он ложно-положительный, т.к. у тебя все вопросы одинаковые. и тест пройдет, даже если на странице выведен только первый ответ, просто проверка выполнится три  раза. Надо сделать вопросы разными, например, через sequence в фабриках

2019-04-17 07:28 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +    question.answers.each do |answer|
ответы тоже должны быть разными

2019-04-17 08:04 UTC, MrAlejandro commented on app/controllers/answers_controller.rb
> +    current_user.save
done

2019-04-17 08:37 UTC, MrAlejandro commented on app/controllers/answers_controller.rb
> +    redirect_to @question, notice: @answer.errors.full_messages.join(', ')
done

2019-04-17 08:48 UTC, MrAlejandro commented on app/controllers/questions_controller.rb
> +    if question.author?(current_user)
done

2019-04-17 08:48 UTC, MrAlejandro commented on app/helpers/answers_helper.rb
> +  def answer
done

2019-04-17 08:50 UTC, MrAlejandro commented on app/models/answer.rb
> +    user && author.id == user.id
done

2019-04-17 09:18 UTC, MrAlejandro commented on app/models/question.rb
> +  def author?(user)
Да, дублирование смутило, но в юзера не хотел переносить - казалось что не его зона ответственности.
Тесты не написал, потому что это в каком то виде тестируется через тесты контроллеров.
done

2019-04-17 09:31 UTC, MrAlejandro commented on app/views/layouts/application.html.erb
>    </head>
done

2019-04-17 09:31 UTC, MrAlejandro commented on app/views/questions/new.html.slim
> += form_with model: question do |f|
done

2019-04-17 09:31 UTC, MrAlejandro commented on app/views/questions/show.html.slim
> += @answers.each do |answer|
done

2019-04-17 09:32 UTC, MrAlejandro commented on app/views/questions/show.html.slim
> += form_with model: [question, answer], local: true do |f|
done

2019-04-17 10:13 UTC, MrAlejandro commented on db/migrate/20190416180144_add_author_id_to_question.rb
> +    add_column :questions, :author_id, :integer
done

2019-04-17 10:13 UTC, MrAlejandro commented on db/migrate/20190416191423_add_author_id_to_answers.rb
> +    add_column :answers, :author_id, :integer
done

2019-04-17 10:20 UTC, MrAlejandro commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
done

2019-04-17 10:29 UTC, MrAlejandro commented on spec/controllers/answers_controller_spec.rb
> +      question.answers = [answer]
done

2019-04-17 10:31 UTC, MrAlejandro commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: answer.id } }.to change(question.answers, :count).by(-1)
done

2019-04-17 10:34 UTC, MrAlejandro commented on spec/controllers/answers_controller_spec.rb
> +    it 'User that does not own the answer cannot delete it' do
done

2019-04-17 10:37 UTC, MrAlejandro commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
done

2019-04-17 10:38 UTC, MrAlejandro commented on spec/controllers/questions_controller_spec.rb
> +      describe 'by owner of the question' do
done

2019-04-17 10:41 UTC, MrAlejandro commented on spec/controllers/questions_controller_spec.rb
> +      describe 'by other user' do
done

2019-04-17 10:42 UTC, MrAlejandro commented on spec/factories/answers.rb
> +    question { create(:question) }
done

2019-04-17 10:47 UTC, MrAlejandro commented on spec/factories/answers.rb
> +    author { create(:user) }
done

2019-04-17 10:49 UTC, MrAlejandro commented on spec/features/answers/destroy_spec.rb
> +  scenario 'User can delete answer that belongs to him' do
я кнопку не вывожу для если не автор https://github.com/MrAlejandro/qna/pull/3/files#diff-7c77b3865a9eaa81c10dff19d3b744efR4

2019-04-17 10:53 UTC, MrAlejandro commented on spec/features/answers/destroy_spec.rb
> +    expect(page).to have_content 'Answer has been deleted.'
done

2019-04-17 11:48 UTC, MrAlejandro commented on spec/features/question/destroy_spec.rb
> +feature 'User can delete question', %q{
проверки добавил, а кнопку удаления я тоже вывожу только для для автора.

2019-04-17 11:48 UTC, MrAlejandro commented on spec/features/question/index_spec.rb
> +    questions.each do |question|
done

2019-04-17 11:50 UTC, MrAlejandro commented on spec/features/question/show_spec.rb
> +    question.answers.each do |answer|
done

2019-04-17 16:10 UTC, vkurennov commented on spec/features/answers/destroy_spec.rb
> +  scenario 'User can delete answer that belongs to him' do
вот это и надо проверить, что кнопка не видна.

2019-04-17 16:13 UTC, vkurennov requested changes

2019-04-17 16:13 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: first_question.id } }.to_not change(question.answers, :count)
тут тоже просто Answer в change

2019-04-17 16:13 UTC, vkurennov commented on spec/models/user_spec.rb
> +    expect(question.author.author?(question)).to be true
лучше так: `expect(user).to be_author_of(question)`

2019-04-17 16:13 UTC, vkurennov approved these changes

2019-04-18 05:50 UTC, MrAlejandro commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: first_question.id } }.to_not change(question.answers, :count)
done

2019-04-18 05:55 UTC, MrAlejandro commented on spec/models/user_spec.rb
> +    expect(question.author.author?(question)).to be true
done

2019-04-18 06:04 UTC, MrAlejandro commented on spec/features/answers/destroy_spec.rb
> +  scenario 'User can delete answer that belongs to him' do
done

2019-04-18 06:11 UTC, merged