Ajax logic implemented.
MrAlejandro/qna pull request #4
Opened 2019-04-17 17:43 UTC by MrAlejandro

2019-04-19 12:33 UTC, vkurennov requested changes

2019-04-19 12:33 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      unselect_best_answer!(@question.answers)
Контроллер не должен содержать логики по назначению лучшего ответа, он должен вызвать один метод модели, а этот метод уже должен все сделать. И т.к. там несколько апдейтов, то их нужно будет обернуть в транзакцию, чтобы изменения были атомарными.

Иными словами, не важно откуда мы производим действие (из контроллера или из консоли или из другой модели), у ответа должен быть метод, вызвав который он станет лучшим, а другие перестанут быть таковыми (т.е. не несколько методов для одной опреации надо вызывать, а один)

2019-04-19 12:33 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    render :best
это лишнее, по-умолчанию, рельсы и так рендерят вид по имени экшена. считай, что эта строчка уже есть

2019-04-19 12:33 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    render :destroy
тоже лишнее

2019-04-19 12:33 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    render :update
лишнее

2019-04-19 12:33 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def answers_best_first(question)
этому не место в контроллере, ты перегружаешь его логикой и работой с данными, а это отвественность моделей. И в моделях есть такая штука как скоупы, которая как раз здесь пригодится.

2019-04-19 12:33 UTC, vkurennov commented on app/models/answer.rb
> +  def best?
рельсы автоматом создают такие методы для boolean-атрибутов, так что такой метод уже есть

2019-04-19 12:33 UTC, vkurennov commented on app/views/answers/update.js.erb
> +$('.answers').html('<%= j render @question.answers %>');
тут надо обновлять только измененный ответ, а не весь список

2019-04-19 13:28 UTC, MrAlejandro commented on app/controllers/answers_controller.rb
> +    render :best
done

2019-04-19 13:28 UTC, MrAlejandro commented on app/controllers/answers_controller.rb
> +    render :destroy
done

2019-04-19 13:28 UTC, MrAlejandro commented on app/controllers/questions_controller.rb
> +    render :update
done

2019-04-19 13:28 UTC, MrAlejandro commented on app/models/answer.rb
> +  def best?
removed

2019-04-19 13:28 UTC, MrAlejandro commented on app/controllers/answers_controller.rb
> +      unselect_best_answer!(@question.answers)
done

2019-04-19 13:40 UTC, MrAlejandro commented on app/controllers/questions_controller.rb
> +  def answers_best_first(question)
done

2019-04-19 13:56 UTC, MrAlejandro commented on app/views/answers/update.js.erb
> +$('.answers').html('<%= j render @question.answers %>');
done

2019-04-19 14:26 UTC, vkurennov requested changes

2019-04-19 14:26 UTC, vkurennov commented on app/models/answer.rb
> +  scope :for_question, ->(question_id) { where(question_id: question_id) }
это лишнее, потому что если у тебя есть вопрос, то ты всегда можешь получить его ответы через ассоциацию вопроса: `questions.answers`,

2019-04-19 14:26 UTC, vkurennov commented on app/models/answer.rb
> +      update(best: true)
только `update!`, т.к. транзакция откатывается только в случае исключения

2019-04-19 14:26 UTC, vkurennov commented on app/models/answer.rb
> +  def mark_as_best!
А где тесты модели на этот метод?

2019-04-30 16:13 UTC, MrAlejandro commented on app/models/answer.rb
> +  scope :for_question, ->(question_id) { where(question_id: question_id) }
done

2019-04-30 16:13 UTC, MrAlejandro commented on app/models/answer.rb
> +      update(best: true)
done

2019-04-30 16:29 UTC, MrAlejandro commented on app/models/answer.rb
> +  def mark_as_best!
added

2019-04-30 21:29 UTC, vkurennov approved these changes

2019-05-01 04:21 UTC, merged