8 action cable
MrAlejandro/qna pull request #9
Opened 2019-05-11 17:31 UTC by MrAlejandro

2019-05-12 08:28 UTC, vkurennov requested changes

2019-05-12 08:28 UTC, vkurennov commented on app/assets/javascripts/answers.js
> +        this.perform('follow', {resource: 'answer', id: answer_id});
это очень ресурсоемко делать отдельный стрим на каждый ответ. да и бессмысленно. сделай общий стрим для комментариев для вопроса и его ответов и уже на основе данных, полученных от сервера, разбирай куда нужно добавить комментарий

2019-05-12 08:28 UTC, vkurennov commented on app/assets/javascripts/templates/answer.jst.skim
> +  - if @author_id == gon.user_id
тебе вообще не надо автору рендерить ничего, т.к. ему придет ответ от сервера (js.erb), иначе, он может увидеть дублированные данные. надо прямо на клиенте делать проверку и если это автор, то ничего ему не рендерить.

2019-05-12 08:28 UTC, vkurennov commented on app/controllers/concerns/commented.rb
> +module Commented
комментарии нужно сделать отдельным ресурсом (контроллером), потому что это и есть отдельный ресурс, а не составная часть вопроса/ответа.

2019-05-12 08:28 UTC, vkurennov commented on app/models/concerns/commentable.rb
> +module Commentable
и это лишнее, не нужны здесь консерны

2019-05-12 12:48 UTC, MrAlejandro commented on app/controllers/concerns/commented.rb
> +module Commented
done

2019-05-12 12:56 UTC, MrAlejandro commented on app/assets/javascripts/answers.js
> +        this.perform('follow', {resource: 'answer', id: answer_id});
done

2019-05-12 12:58 UTC, MrAlejandro commented on app/models/concerns/commentable.rb
> +module Commentable
done

2019-05-12 12:59 UTC, MrAlejandro commented on app/assets/javascripts/templates/answer.jst.skim
> +  - if @author_id == gon.user_id
done

2019-05-13 07:42 UTC, vkurennov approved these changes

2019-05-13 13:42 UTC, merged